language: objective-c
xcode_workspace: Webpay.xcworkspace
xcode_scheme: Webpay
xcode_sdk: iphonesimulator7.0
before_install:
  - brew update
  - if brew outdated | grep -qx <package-name>; then brew upgrade <package-name>; fi
  - gem install cocoapods -v '0.32.1'

script:
  - xctool -workspace Webpay.xcworkspace -scheme Webpay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Webpay.xcworkspace -scheme Webpay -sdk iphonesimulator7.0 -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" ONLY_ACTIVE_ARCH=NO
