language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_workspace: Webpay.xcworkspace
xcode_scheme: WebpayTests
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem install cocoapods

